### ISSUE TITLE
Does not build on Ubuntu 20.04

### ISSUE THREAD

**Issue by ghost** [Telecommunication-Telemedia-Assessment/SITI#15]
Hi!

As I understand Ubuntu 20.04 should be supported platform to build this useful tool. Unfortunately following documentation steps does not appear to work.

The reproducable  steps in followinf Dockerfile:
```
FROM docker.io/ubuntu:20.04

WORKDIR /app

# Enable contrin and bob-free repositories.

RUN sed -i 's/main/main contrib non-free/g' /etc/apt/sources.list

RUN apt-get update && apt-get -y install \
	build-essential \
	scons \
	libopencv-dev \
	curl \
	unzip \
&& rm -rf /var/lib/apt/lists/*

RUN curl -L -o SITI.zip https://github.com/Telecommunication-Telemedia-Assessment/SITI/archive/master.zip \
	&& unzip SITI.zip

RUN cd SITI-master/src/SITI \
	&& scons
```

Which results in following build error:
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o main.o -c -std=c++11 -O3 -g main.cpp
main.cpp:28:10: fatal error: opencv2/opencv.hpp: No such file or directory
   28 | #include <opencv2/opencv.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [main.o] Error 1
scons: building terminated because of errors.
```

Sorry, I am not familiar with `scons` to do any meaningful troubleshooting.

On the other hand running `g++` directly:
```
# g++ -I/usr/include/opencv4/ -o SITI -std=c++11 -O3 main.cpp
/usr/bin/ld: /tmp/ccOC6ZlU.o: in function `grabFrame(cv::Mat&, cv::VideoCapture&)':
main.cpp:(.text+0x74f): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text+0x7eb): undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
/usr/bin/ld: main.cpp:(.text+0x83c): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: /tmp/ccOC6ZlU.o: in function `computeSI(cv::Mat const&, cv::Mat const&)':
main.cpp:(.text+0xa0c): undefined reference to `cv::Sobel(cv::_InputArray const&, cv::_OutputArray const&, int, int, int, int, double, double, int)'
/usr/bin/ld: main.cpp:(.text+0xa87): undefined reference to `cv::Sobel(cv::_InputArray const&, cv::_OutputArray const&, int, int, int, int, double, double, int)'
/usr/bin/ld: main.cpp:(.text+0xa9c): undefined reference to `cv::noArray()'
/usr/bin/ld: main.cpp:(.text+0xb18): undefined reference to `cv::Mat::mul(cv::_InputArray const&, double) const'
/usr/bin/ld: main.cpp:(.text+0xb7c): undefined reference to `cv::Mat::mul(cv::_InputArray const&, double) const'
/usr/bin/ld: main.cpp:(.text+0xbc8): undefined reference to `cv::add(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, int)'
/usr/bin/ld: main.cpp:(.text+0xc4e): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text+0xcd6): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text+0xd5e): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text+0xde3): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text+0xe6e): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: /tmp/ccOC6ZlU.o:main.cpp:(.text+0xef6): more undefined references to `cv::fastFree(void*)' follow
/usr/bin/ld: /tmp/ccOC6ZlU.o: in function `computeSI(cv::Mat const&, cv::Mat const&)':
main.cpp:(.text+0xf40): undefined reference to `cv::sqrt(cv::_InputArray const&, cv::_OutputArray const&)'
/usr/bin/ld: main.cpp:(.text+0x1000): undefined reference to `cv::meanStdDev(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_InputArray const&)'
/usr/bin/ld: main.cpp:(.text+0x1084): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text+0x10f4): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text+0x1164): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text+0x119c): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text+0x11b0): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text+0x11c8): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text+0x11e0): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text+0x11f8): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: /tmp/ccOC6ZlU.o:main.cpp:(.text+0x1210): more undefined references to `cv::Mat::deallocate()' follow
/usr/bin/ld: /tmp/ccOC6ZlU.o: in function `cv::Mat::~Mat()':
main.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x5e): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x69): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: /tmp/ccOC6ZlU.o: in function `main.cold':
main.cpp:(.text.unlikely+0x34e): undefined reference to `cv::VideoCapture::~VideoCapture()'
/usr/bin/ld: /tmp/ccOC6ZlU.o: in function `cv::Mat::create(int, int, int)':
main.cpp:(.text._ZN2cv3Mat6createEiii[_ZN2cv3Mat6createEiii]+0x39): undefined reference to `cv::Mat::create(int, int const*, int)'
/usr/bin/ld: /tmp/ccOC6ZlU.o: in function `cv::MatExpr::~MatExpr()':
main.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x77): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0xe4): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x13e): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x14d): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x160): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text._ZN2cv7MatExprD2Ev[_ZN2cv7MatExprD5Ev]+0x175): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: /tmp/ccOC6ZlU.o: in function `main':
main.cpp:(.text.startup+0xc06): undefined reference to `cv::VideoCapture::VideoCapture()'
/usr/bin/ld: main.cpp:(.text.startup+0x115a): undefined reference to `cv::Mat::create(int, int const*, int)'
/usr/bin/ld: main.cpp:(.text.startup+0x11b7): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x11c2): undefined reference to `cv::Mat::operator=(cv::Scalar_<double> const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x123f): undefined reference to `cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const'
/usr/bin/ld: main.cpp:(.text.startup+0x12f7): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/usr/bin/ld: main.cpp:(.text.startup+0x1336): undefined reference to `cv::Mat::convertTo(cv::_OutputArray const&, int, double, double) const'
/usr/bin/ld: main.cpp:(.text.startup+0x13b0): undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
/usr/bin/ld: main.cpp:(.text.startup+0x13c8): undefined reference to `cv::operator/(cv::Mat const&, double)'
/usr/bin/ld: main.cpp:(.text.startup+0x141a): undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x14aa): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text.startup+0x152a): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text.startup+0x15aa): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text.startup+0x15b4): undefined reference to `cv::waitKey(int)'
/usr/bin/ld: main.cpp:(.text.startup+0x162c): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text.startup+0x1691): undefined reference to `cv::noArray()'
/usr/bin/ld: main.cpp:(.text.startup+0x170d): undefined reference to `cv::subtract(cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, int)'
/usr/bin/ld: main.cpp:(.text.startup+0x17cf): undefined reference to `cv::meanStdDev(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_InputArray const&)'
/usr/bin/ld: main.cpp:(.text.startup+0x1a21): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text.startup+0x1b2d): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text.startup+0x1baa): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text.startup+0x1c28): undefined reference to `cv::fastFree(void*)'
/usr/bin/ld: main.cpp:(.text.startup+0x1cfe): undefined reference to `cv::VideoCapture::~VideoCapture()'
/usr/bin/ld: main.cpp:(.text.startup+0x1e94): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text.startup+0x1f66): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text.startup+0x1f78): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text.startup+0x1f8a): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text.startup+0x1f9c): undefined reference to `cv::Mat::deallocate()'
/usr/bin/ld: main.cpp:(.text.startup+0x26d5): undefined reference to `cv::VideoCapture::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/usr/bin/ld: main.cpp:(.text.startup+0x26e2): undefined reference to `cv::VideoCapture::isOpened() const'
/usr/bin/ld: main.cpp:(.text.startup+0x271f): undefined reference to `cv::VideoCapture::get(int) const'
/usr/bin/ld: main.cpp:(.text.startup+0x2734): undefined reference to `cv::VideoCapture::get(int) const'
collect2: error: ld returned 1 exit status
```

**Comment by slhck** [comment]
Please see https://github.com/Telecommunication-Telemedia-Assessment/SITI/issues/13 - does that solve the problem?

**Comment by ghost** [comment]
@slhck Thanks for prompt response. What exactly you suggest I take from #13 ?

I have installed opencv libs as per instructions:
```
I# dpkg -l libopencv-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libopencv-dev  4.2.0+dfsg-5 amd64        development files for opencv
```

Do you mean I need to try from `opencv4-check` branch?

**Comment by ghost** [comment]
OK, building from `opencv4-check` worked. But it seems that leaves `master` branch broken both on Ubuntu 18.04 and 20.04.

**Comment by slhck** [comment]
Yes, please check the other branch. I'll have to check with @stg7 whether we can provide a build for both OS versions. I am not too familiar with OpenCV and scons myself.

**Comment by slhck** [comment]
Ah I see. My understanding was that 18.04 still worked. In that case we can probably just merge the branch. I'll check it later. Thanks for the feedback!

**Comment by stg7** [comment]
i added a "check" for opencv or opencv4 (see 6bde87a734442731b2ef85b255108101e1bf0d58), this works for ubuntu 18.04 and 20.04, however for 16.04 it does not work, but i think 16.04 is not required anymore?
does this "hack" work for macos?

**Comment by slhck** [comment]
Yes, it works under macOS! (Tested with 10.15)

I think we can safely drop support for 16.04.

**Comment by stg7** [comment]
yes, i also think support for 16.04 is not required, however in case of 16.04 the error was related to the header files, thus the opencv version is even older, i further tested 21.04 with the "hack" and there it also works like butter, so i think we can merge this to master?

**Comment by slhck** [comment]
Looks good, thanks for merging!

@jurisbu Can we use your Dockerfile as a starting point for providing our own?
