### ISSUE TITLE
build on Ubuntu 16.04

### ISSUE THREAD

**Issue by haiqwang** [Telecommunication-Telemedia-Assessment/SITI#20]
I was trying to build on Ubuntu 16.04 following the given instructions. Unfortunately, I run into the config error related to opencv. 

`main.cpp:28:28: fatal error: opencv2/core.hpp: No such file or directory`

I also found that this repo no longer supports 16.04 #13 . 
What are the modifications needed to compile on 16.04?

**Comment by slhck** [comment]
You can see the modifications made at the time here: https://github.com/Telecommunication-Telemedia-Assessment/SITI/pull/16/files

That said, if you want a quick solution that works on any operating system, you can use a Python version. There is a library [here](https://github.com/Telecommunication-Telemedia-Assessment/siti-tools) and a CLI version [here](https://github.com/slhck/siti). There is also [another Python script](https://github.com/Telecommunication-Telemedia-Assessment/SITI/tree/master/python) in this repo, but it has minor inconsistencies with respect to the other libraries.

**Comment by haiqwang** [comment]
Got it. Thanks.
